src/newsapp/urls.py
from django.shortcuts import render

# Create your views here.
from django.urls import path
from . import views

app_name = 'newsapp'

urlpatterns = [
    path('read_news/<str:q>/', views.choice_topic, name="read_news"),
    path('detail_paragraph/<str:q>/', views.paragraph, name="detail_paragraph"),
    ]

src/notesapp/urls.py
from django.urls import path
from . import views

app_name = 'notesapp'

urlpatterns = [
    path('search_note/', views.search_note, name="search_note"),
    path('search_tag/', views.search_tag, name="search_tag"),
    path('add_tag/', views.add_tag, name="add_tag"),
    path('add_note/', views.add_note, name="add_note"),
    path('detail_note/<int:note_id>', views.detail_note, name="detail_note"),
    path('detail_tag/<int:tag_id>', views.detail_tag, name="detail_tag"),
    path('delete_note/<int:note_id>', views.delete_note, name="delete_note"),
    path('delete_tag/<int:tag_id>', views.delete_tag, name="delete_tag"),
    path('edit_note/<int:note_id>', views.edit_note, name="edit_note"),
]

src/personal_assistant/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from usersapp.views import root

urlpatterns = [
    path('', root, name='root'),
    path('admin/', admin.site.urls),
    path('users/', include('usersapp.urls')),
    path('bot/', include('ai_chat_bot.urls')),
    path('contacts/', include('contactsapp.urls')),
    path('notes/', include('notesapp.urls')),
    path('news/', include('newsapp.urls')),
    path('cloud_storageapp/', include('cloud_storageapp.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/notesapp/models.py
from django.db import models
from usersapp.models import CustomUser


class Tag(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    name = models.CharField(max_length=255, blank=False)


class Note(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    title = models.CharField(max_length=255, blank=False)
    description = models.TextField(blank=False)
    tags = models.ManyToManyField(Tag)

    def __str__(self):
        return self.title

src/notesapp/forms.py
from django.forms import ModelForm, CharField, TextInput, Textarea, Form
from . import models


class TagForm(ModelForm):
    name = CharField(required=True)

    class Meta:
        model = models.Tag
        fields = ['name']


class NoteForm(ModelForm):
    title = CharField(required=True)
    description = CharField(required=True)

    class Meta:
        model = models.Note
        fields = ['title', 'description']
        exclude = ['tags']

src/notesapp/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from .forms import TagForm, NoteForm
from .models import Tag, Note
from django.db import models


@login_required
def search_note(request):
    search_query_note = request.GET.get('search_query', '')
    user_notes = Note.objects.filter(user=request.user)
    search_results_note = user_notes.filter(title__icontains=search_query_note)
    if search_query_note == ' ' or search_query_note == 'all':
        context = {
            'search_query_note': search_query_note,
            'all_notes': user_notes,
        }
        return render(request, 'notesapp/search_note.html', context)

    else:
        context = {
            'search_query_note': search_query_note,
            'search_results_note': search_results_note,
        }

        return render(request, 'notesapp/search_note.html', context)


@login_required
def search_tag(request):
    search_query_tag = request.GET.get('search_query', '')
    user_tags = Tag.objects.filter(user=request.user)
    search_results_tag = user_tags.filter(name__icontains=search_query_tag)

    if search_query_tag == ' ' or search_query_tag == 'all':
        context = {
            'search_query_tag': search_query_tag,
            'all_tags': user_tags
        }
        return render(request, 'notesapp/search_tag.html', context)

    else:
        context = {
            'search_query_tag': search_query_tag,
            'search_results_tag': search_results_tag
        }

        return render(request, 'notesapp/search_tag.html', context)


@login_required
def add_tag(request):
    if request.method == 'POST':
        form = TagForm(request.POST)
        if form.is_valid():
            tag = form.save(commit=False)
            tag.user = request.user
            tag.save()
            return redirect(to='usersapp:success')
        else:
            return render(request, 'notesapp/add_tag.html', context={'form': form})

    return render(request, 'notesapp/add_tag.html', context={'form': TagForm()})


@login_required
def add_note(request):
    tags = Tag.objects.filter(user=request.user).all()
    if request.method == 'POST':
        form = NoteForm(request.POST)
        if form.is_valid():
            note = form.save(commit=False)
            note.user = request.user
            note.save()
            choice_tags = Tag.objects.filter(name__in=request.POST.getlist('tags'), user=request.user)
            for tag in choice_tags:
                note.tags.add(tag)
            return redirect(to='usersapp:success')
        else:
            return render(request, 'notesapp/add_note.html', context={'form': form, 'tags': tags})

    return render(request, 'notesapp/add_note.html', context={'form': NoteForm(), 'tags': tags})


@login_required
def edit_note(request, note_id):
    note = get_object_or_404(Note, pk=note_id, user=request.user)
    tags = Tag.objects.filter(user=request.user).all()
    if request.method == 'POST':
        form = NoteForm(request.POST, instance=note)
        if form.is_valid():
            note = form.save(commit=False)
            note.user = request.user
            note.tags.clear()
            note.save()
            choice_tags = Tag.objects.filter(name__in=request.POST.getlist('tags'),
                                             user=request.user)
            for tag in choice_tags:
                note.tags.add(tag)
            return redirect(to="notesapp:detail_note", note_id=note_id)
    else:
        form = NoteForm(instance=note)
    return render(request, 'notesapp/edit_note.html',
                  context={'form': form, 'note': note, 'tags': tags})


@login_required
def detail_note(request, note_id):
    note = get_object_or_404(Note, pk=note_id, user=request.user)
    return render(request, 'notesapp/detail_note.html', context={"note": note})


@login_required
def detail_tag(request, tag_id):
    tag = Tag.objects.filter(id=tag_id).first()
    notes = Note.objects.filter(tags=tag_id).all()
    return render(request, 'notesapp/detail_tag.html', context={"tag": tag, "notes": notes})


@login_required
def delete_note(request, note_id):
    note = get_object_or_404(Note, pk=note_id, user=request.user)
    if request.method == 'POST':
        note.delete()
        return redirect(to='usersapp:success')
    return render(request, 'notesapp/delete_note.html', {'note': note})


@login_required
def delete_tag(request, tag_id):
    tag = get_object_or_404(Tag, pk=tag_id, user=request.user)
    if request.method == 'POST':
        tag.delete()
        return redirect(to='usersapp:success')
    return render(request, 'notesapp/delete_tag.html', {'tag': tag})


@login_required
def tag_sort(request, tag_id):
    tags = Tag.objects.filter(id=tag_id).first()
    notes = Note.objects.filter(tags=tag_id).all()
    return render(request, 'notesapp/tag_sort.html', {'notes': notes, 'tags': tags})

src/notesapp/templates/notesapp/add_note.html
{% extends "usersapp/base.html" %}

{% block content %}

<div class="container h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-12 col-md-6 col-lg-6 col-xl-5">
            <div class="card" style="border-radius: 15px;">
                <div class="card-body p-5">
                    <h2 class="text-uppercase text-center mb-3">Add Note</h2>
                    {% if form.errors %}
                    <span class="alert alert-danger" role="alert">{{form.non_field_errors}}</span>
                    {% endif %}
    <form class="container me-2" method="POST" action="{% url 'notesapp:add_note' %}">
        {% csrf_token %}
        <div class="form-outline mb-2">
            <label class="form-label">Add title*: {{ form.title }}</label>
        <span>{{form.errors.title}}</span>
        </div>
        <div class="form-outline mb-2">
            <label class="form-label">Add description*: {{ form.description }}</label>
        <span>{{form.errors.description}}</span>
        </div>
        <div style="container me-2">
        <label> Select tags*:
            <select name="tags" multiple="multiple" required>
                {% for tag in tags %}
                <option value="{{tag.name}}">{{tag.name}}</option>
                {% endfor %}
            </select>
        </label>
        </div>
         <div class="d-flex justify-content-center button-container">
            <button type="submit" class="btn btn-success btn-block btn-lg gradient-custom-5 text-body">Save</button>
            <button type="reset" class="btn btn-success btn-block btn-lg gradient-custom-5 text-body">Reset</button>
         </div>
    </form>
</div>
</div>
</div>
</div>
</div>
{% endblock %}

src/notesapp/templates/notesapp/add_tag.html
{% extends "usersapp/base.html" %}

{% block content %}

<div class="container h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-12 col-md-6 col-lg-6 col-xl-5">
            <div class="card" style="border-radius: 15px;">
                <div class="card-body p-5">
                    <h2 class="text-uppercase text-center mb-3">Add Tag</h2>
                    {% if form.errors %}
                    <span class="alert alert-danger" role="alert">{{form.non_field_errors}}</span>
                    {% endif %}
    <form class="container me-2" method="POST" action="{% url 'notesapp:add_tag' %}">
        {% csrf_token %}
        <div class="form-outline mb-2">
            <label class="form-label">Add tag*: {{ form.name }}</label>
        <span>{{form.errors.name}}</span>
        </div>
         <div class="d-flex justify-content-center button-container">
            <button type="submit" class="btn btn-success btn-block btn-lg gradient-custom-5 text-body">Submit</button>
            <button type="reset" class="btn btn-success btn-block btn-lg gradient-custom-5 text-body">Reset</button>
         </div>
    </form>
</div>
</div>
</div>
</div>
</div>

{% endblock %}

src/notesapp/templates/notesapp/delete_note.html
{% extends "usersapp/base.html" %}

{% block content %}
<div class="container h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-12 col-md-6 col-lg-6 col-xl-5">
            <div class="card" style="border-radius: 15px;">
                <div class="card-body p-5">
                    <h2 class="text-uppercase text-center mb-3">Delete Note</h2>
    <form class="form-control border" method="POST" action="{% url 'notesapp:delete_note' note.id %}">
        {% csrf_token %}
        <div class="d-flex flex-column align-items-center">
            <div class="my-2">Are you sure you want to delete the note "{{ note.title }}"?</div>
            <button class="btn btn-success btn-block btn-lg gradient-custom-5 text-body col-8" type="submit">Yes</button>
            <button class="btn btn-success btn-block btn-lg gradient-custom-5 text-body col-8"  type="button" onclick="history.back()">No</button>
        </div>
    </form>
</div>
</div>
</div>
</div>
</div>
{% endblock %}

src/notesapp/templates/notesapp/delete_tag.html
{% extends "usersapp/base.html" %}

{% block content %}
<div class="container h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-12 col-md-6 col-lg-6 col-xl-5">
            <div class="card" style="border-radius: 15px;">
                <div class="card-body p-5">
                    <h2 class="text-uppercase text-center mb-3">Delete Tag</h2>
    <form class="form-control border" method="POST" action="{% url 'notesapp:delete_tag' tag.id %}">
        {% csrf_token %}
        <div class="d-flex flex-column align-items-center">
            <div class="my-2">Are you sure you want to delete the tag "{{ tag.name }}"?</div>
            <button class="btn btn-success btn-block btn-lg gradient-custom-5 text-body col-8" type="submit">Yes</button>
            <button class="btn btn-success btn-block btn-lg gradient-custom-5 text-body col-8"  type="button" onclick="history.back()">No</button>
        </div>
    </form>
</div>
</div>
</div>
</div>
</div>
{% endblock %}

src/notesapp/templates/notesapp/detail_note.html
{% extends "usersapp/base.html" %}
{% load extract_tags %}
{% block content %}
<style>
.btn-container {
margin-right: 10px;
}
</style>
<div class="container my-1">
    {% if note %}
        <h4 class="text-center">Results for Note "{{ note.title }}"</h4>
        <div class="container my-1">
            <div class="form-control d-flex flex-row">
                <div class="flex-fill">
                    <strong>Title:</strong> {{ note.title }}<br>
                    <strong>Description:</strong> {{ note.description }}<br>
                    <strong>Tags:</strong>
                    {% for tag in note.tags.all %}
                    <a href="{% url 'notesapp:detail_tag' tag.id %}">{{tag.name}},</a>
                    {% endfor %}
                </div>
                <div class="d-flex align-items-center">
                    <div class="btn-container">
                        <a class="btn btn-success btn-block btn-lg gradient-custom-5 text-body"  href="{% url 'notesapp:edit_note' note.id %}">Edit Note</a><br>
                    </div>
                    <div class="btn-container">
                        <a class="btn btn-success btn-block btn-lg gradient-custom-5 text-body"  href="{% url 'notesapp:delete_note' note.id %}">Delete</a>
                    </div>
                </div>
            </div>
        </div>
    <div align="right"><button class="btn btn-success btn-block btn-lg gradient-custom-5 text-body col-2" type="button" onclick="history.back()">Back</button></div>
    {% endif %}
</div>
{% endblock %}

src/notesapp/templates/notesapp/detail_tag.html
{% extends "usersapp/base.html" %}

{% block content %}
<div class="container my-1">
        <h4 class="text-center">Results for Tag "{{ tag.name }}"</h4>
        <div class="container my-1">
            <div class="form-control d-flex flex-row">
                <div class="flex-fill">
                    <strong>Tag:</strong> {{tag.name}}<br><hr>
                    {% for note in notes %}
                    <strong>Title:</strong><a href="{% url 'notesapp:detail_note' note.id %}"> {{ note.title }}</a> <br>
                    <strong>Description:</strong> {{ note.description }}<br><hr>
                    {% endfor %}
                </div>
                <div class="d-flex align-items-center">
                    <a class="btn btn-success btn-block btn-lg gradient-custom-5 text-body"  href="{% url 'notesapp:delete_tag' tag.id %}">Delete</a>
                </div>
            </div>
        </div>
    <div align="right"><button class="btn btn-success btn-block btn-lg gradient-custom-5 text-body col-2" type="button" onclick="history.back()">Back</button></div>
</div>
{% endblock %}

src/notesapp/templates/notesapp/edit_note.html
{% extends "usersapp/base.html" %}

{% block content %}

<div class="container h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-12 col-md-6 col-lg-6 col-xl-5">
            <div class="card" style="border-radius: 15px;">
                <div class="card-body p-5">
                    <h2 class="text-uppercase text-center mb-3">Edit Note</h2>
                    {% if form.errors %}
                    <span class="alert alert-danger" role="alert">{{form.non_field_errors}}</span>
                    {% endif %}
    <form class="container me-2" method="POST" action="{% url 'notesapp:edit_note' note.id %}">
        {% csrf_token %}
        <div class="form-outline mb-2">
            <label class="form-label">Edit title*: {{ form.title }}</label>
        <span>{{form.errors.title}}</span>
        </div>
        <div class="form-outline mb-2">
            <label class="form-label">Edit description*: {{ form.description }}</label>
        <span>{{form.errors.description}}</span>
        </div>
        <div style="container me-2">
        <label> Select tags*:
            <select name="tags" multiple="multiple" required>
                {% for tag in tags %}
                <option value="{{tag.name}}">{{tag.name}}</option>
                {% endfor %}
            </select>
        </label>
        </div>
         <div class="d-flex justify-content-center button-container">
            <button type="submit" class="btn btn-success btn-block btn-lg gradient-custom-5 text-body">Save</button>
         </div>
    </form>
</div>
</div>
</div>
</div>
</div>

{% endblock %}

src/notesapp/templates/notesapp/search_note.html
{% extends "usersapp/base.html" %}

{% block content %}
<style>
.custom-container {
    width: 100%;
    margin: 0 auto; /* To center the container horizontally */
    }

.scroll-table-body {
  text-align: center;
 height: 700px;
 overflow-x: center;
 margin-top: 0px;
 margin-bottom: 20px;
 border-bottom: 1px solid #eee;
}
.scroll-table table {
 text-align: center;
 width:100%;
 table-layout: fixed;
 border: 1px solid #ddd;
}
.scroll-table thead th {
 font-weight: bold;
 text-align: center;
 border: none;
 padding: 10px 15px;
 background: #b3b3b3;
 font-size: 14px;
 border-left: 1px solid #ddd;
 border-right: 1px solid #ddd;
}
.scroll-table tbody td {
 text-align: center;
 border-left: 1px solid #ddd;
 border-right: 1px solid #ddd;
 padding: 10px 15px;
 font-size: 14px;
 vertical-align: top;
}
.scroll-table tbody tr:nth-child(even){
 text-align: center;
 background: #b3b3b3;
}
.table {
        text-align: center;
        background-color: #C5F2F3;
        padding: 10px;
        color: #DE00FF;

    }
.my-table {
        text-align: center;
        background-color: #C5F2F3;
        padding: 10px;
        color: #616161;
}
/* Стили для скролла */
::-webkit-scrollbar {
 width: 6px;
}
::-webkit-scrollbar-track {
 box-shadow: inset 0 0 6px rgba(0,0,0,0.3);
}
::-webkit-scrollbar-thumb {
 box-shadow: inset 0 0 6px rgba(0,0,0,0.3);
}

td{
text-align: center;
}

th{
text-align: center;
color: #b3b3b3;
}
</style>

<div class="container my-2">
<!--    <h4 class="text-center">Search by Note ('all' or space to display all note)</h4>-->
    <form class="d-flex" role="search" method="GET" action="{% url 'notesapp:search_note' %}">
        <input class="form-control me-2" name="search_query" type="search" placeholder="Search by Note ('all' or space to display all notes)" aria-label="Search">
        <button class="btn btn-outline-success" type="submit" class="btn btn-warning"
                style="padding: 5px 10px;">Search
        </button>
    </form>

{% if search_query_note %}
<h4 class="text-center">Search results for "{{ search_query_note }}"</h4>
{% if all_notes %}
        <div class="custom-container m-10">
            <div class="text-center">
                <div class="scroll-table">
                    <table class="table">
                        <thead>
                        <tr class="tr">
                            <th><strong>Title</strong></th>
                            <th><strong>Description</strong></th>
                            <th><strong>Tags</strong>
                            </th>
                        </tr>
                        {% for note in all_notes %}
                        <tr>
                            <td><a href="{% url 'notesapp:detail_note' note.id %}">{{note.title}}</a></td>
                            <td>{{note.description}}</td>
                            <td>
                                {% for tag in note.tags.all %}
                                <a href="{% url 'notesapp:detail_tag' tag.id %}">{{tag.name}}, </a>
                                {% endfor %}
                            </td>
                        </tr>
                        {% endfor %}
                        </table>
                    </div>
                </div>
            </div>
        </div>
{% endif %}
{% if search_results_note %}
        <div class="custom-container m-10">
            <div class="text-center">
                <div class="scroll-table">
                    <table class="table">
                        <thead>
                        <tr class="tr">
                            <th><strong>Title</strong></th>
                            <th><strong>Description</strong></th>
                            <th><strong>Tags</strong>
                            </th>
                        </tr>
                        {% for note in search_results_note %}
                        <tr>
                            <td><a href="{% url 'notesapp:detail_note' note.id %}">{{note.title}}</a></td>
                            <td>{{note.description}}</td>
                            <td>
                                {% for tag in note.tags.all %}
                                <a href="{% url 'notesapp:detail_tag' tag.id %}">{{tag.name}}, </a>
                                {% endfor %}
                            </td>
                        </tr>
                        {% endfor %}
                        </table>
                    </div>
                </div>
            </div>
{% endif %}
{% endif %}
{% endblock %}

src/notesapp/templates/notesapp/search_tag.html
{% extends "usersapp/base.html" %}

{% block content %}
<style>
.custom-container {
    width: 40%;
    margin: 0 auto; /* To center the container horizontally */
    }

.scroll-table-body {
  text-align: center;
 height: 700px;
 overflow-x: center;
 margin-top: 0px;
 margin-bottom: 20px;
 border-bottom: 1px solid #eee;
}
.scroll-table table {
 text-align: center;
 width:100%;
 table-layout: fixed;
 border: 1px solid #ddd;
}
.scroll-table thead th {
 font-weight: bold;
 text-align: center;
 border: none;
 padding: 10px 15px;
 background: #b3b3b3;
 font-size: 14px;
 border-left: 1px solid #ddd;
 border-right: 1px solid #ddd;
}
.scroll-table tbody td {
 text-align: center;
 border-left: 1px solid #ddd;
 border-right: 1px solid #ddd;
 padding: 10px 15px;
 font-size: 14px;
 vertical-align: top;
}
.scroll-table tbody tr:nth-child(even){
 text-align: center;
 background: #b3b3b3;
}
.table {
        text-align: center;
        background-color: #C5F2F3;
        padding: 10px;
        color: #DE00FF;

    }
.my-table {
        text-align: center;
        background-color: #C5F2F3;
        padding: 10px;
        color: #616161;
}
/* Стили для скролла */
::-webkit-scrollbar {
 width: 6px;
}
::-webkit-scrollbar-track {
 box-shadow: inset 0 0 6px rgba(0,0,0,0.3);
}
::-webkit-scrollbar-thumb {
 box-shadow: inset 0 0 6px rgba(0,0,0,0.3);
}

td{
text-align: center;
}

th{
text-align: center;
color: #b3b3b3;
}
</style>
<div class="container my-2">
<!--    <h4 class="text-center">Search by Contact ('all' or space to display all tag)</h4>-->
        <form class="d-flex" role="search" method="GET" action="{% url 'notesapp:search_tag' %}">
            <input class="form-control me-2" name="search_query" type="search" placeholder="Search by Tag ('all' or space to display all tags)" aria-label="Search">
            <button class="btn btn-outline-success" type="submit" class="btn btn-warning" style="padding: 5px 10px;">Search
        </button>
    </form>


{% if search_query_tag %}
<h4 class="text-center">Search results for "{{ search_query_tag }}"</h4>
{% if all_tags %}
                <div class="custom-container m-10">
                    <div class="text-center">
                        <div class="scroll-table">
                            <table class="table">
                                <thead>
                                <tr class="tr">
                                    <th><strong>Tag</strong>
                                </tr>
                                    {% for tag in all_tags %}
                                <tr>
                                    <td><a href="{% url 'notesapp:detail_tag' tag.id %}">{{tag.name}}</a></td>
                                </tr>
                                {% endfor %}
                            </table>
                        </div>
                    </div>
                </div>
            </div>
{% endif %}
{% if search_results_tag %}
                <div class="custom-container m-10">
                    <div class="text-center">
                        <div class="scroll-table">
                            <table class="table">
                                <thead>
                               <tr class="tr">
                                    <th><strong>Tag</strong>
                                </tr>
                                    {% for tag in search_results_tag %}
                                <tr>
                                    <td><a href="{% url 'notesapp:detail_tag' tag.id %}">{{tag.name}}</a></td>
                                </tr>
                                {% endfor %}
                                </table>
                            </div>
                        </div>
                    </div>
{% endif %}
{% endif %}
{% endblock %}

src/notesapp/templates/notesapp/tag_search.html
{% extends "usersapp/base.html" %}

{% block content %}

        <div class="container my-2">
            <h4 class="text-center">Search results for Tag</h4>
            <div class="container m-10">
                <div class="text-center">
                    <div class="scroll-table">
                        <table class="table">
                            <thead>
                            <tr class="tr">
                                <th scope="col">title</th>
                                <th scope="col">description</th>
                                <th scope="col">tags</th>
                            </tr>
                            </thead>
                        </table>
                        <div class="scroll-table-body">
                            <table class="my-table">
                                <tbody class="my_tr">

                                {% for note in notes %}
                                <tr>
                                    <td><a href="{% url 'notesapp:detail_note' note.id %}">{{note.title}}</a></td>
                                    <td>{{note.description}}</td>
                                    <td>{% for tag in note.tags.all %}
                                        <a href="{% url 'notesapp:tag_search' tag.id %}">{{tag.name}}, </a>
                                        {% endfor %}
                                    </td>
                                </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
{% endblock %}

src/notesapp/templates/notesapp/update_note.html
{% extends "usersapp/base.html" %}

{% block content %}

<div class="container-fluid me-2 pe-3">
    <h4 class="text-center">Update Note</h4>
    <form class="container me-2" method="POST" action="{% url 'notesapp:update_note' note.id  %}">
        {% csrf_token %}
        <div style="container me-2">
            <label class="form-label">Update title*:</label>
            <div class="row col-4">{{form.title}}</div>
        </div>
        <div style="container me-2">
            <label class="form-label">Update description*:</label>
            <div class="row col-4">{{form.description}}</div>
        </div>
        <div style="container me-2">
        <label> Update tags*:
            <select name="tags" multiple="multiple" required>
                {% for tag in tags %}
                <option value="{{tag.name}}">{{tag.name}}</option>
                {% endfor %}
            </select>
        </label>
        </div>
        <div class="grid mt-2">
            <button class="btn btn-success mx-3" type="submit">Save</button>
        </div>
    </form>
</div>

{% endblock %}