src/ai_chat_bot/urls.py
from .views import main, redirect_check
from django.urls import path



app_name = 'ai_chat_bot'

urlpatterns = [
    path('', main, name='main'),
    # path('tg/<str:query>/', redirect_check, name='redirect_check')
    path('redirect_check/<int:query>', redirect_check, name='redirect_check'),

    ]

src/contactsapp/urls.py
from django.urls import path
from . import views
from .views import ContactSendEmail

app_name = 'contactsapp'

urlpatterns = [
    path('add_contact/', views.add_contact, name='add_contact'),
    path('edit_contact/<int:contact_id>', views.edit_contact, name='edit_contact'),
    path('delete_contact/<int:contact_id>', views.delete_contact, name='delete_contact'),
    path('search_contact/', views.search_contact, name='search_contact'),
    path('upcoming_birthdays/', views.upcoming_birthdays, name='upcoming_birthdays'),
    path('detail_contact/<int:contact_id>', views.detail_contact, name="detail_contact"),
    path('<int:id>/email/',  ContactSendEmail.as_view(), name='send_email')
]

src/newsapp/urls.py
from django.shortcuts import render

# Create your views here.
from django.urls import path
from . import views

app_name = 'newsapp'

urlpatterns = [
    path('read_news/<str:q>/', views.choice_topic, name="read_news"),
    path('detail_paragraph/<str:q>/', views.paragraph, name="detail_paragraph"),
    ]

src/personal_assistant/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from usersapp.views import root

urlpatterns = [
    path('', root, name='root'),
    path('admin/', admin.site.urls),
    path('users/', include('usersapp.urls')),
    path('bot/', include('ai_chat_bot.urls')),
    path('contacts/', include('contactsapp.urls')),
    path('notes/', include('notesapp.urls')),
    path('news/', include('newsapp.urls')),
    path('cloud_storageapp/', include('cloud_storageapp.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/contactsapp/models.py
from django.db import models

from django.core.validators import RegexValidator
from django.contrib.postgres.fields import ArrayField
from datetime import datetime
from dateutil.relativedelta import relativedelta

"""To import top-level model from any app"""
from django.contrib.auth import get_user_model


class Contact(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    first_name = models.CharField(blank=False, max_length=255)
    last_name = models.CharField(blank=False, max_length=255)
    address = models.CharField(max_length=255, blank=False)
    phone_regex = RegexValidator(r'^\d{4,20}$', 'only numbers, 4-20 digit')
    phone_number = models.CharField(max_length=20, validators=[phone_regex])
    email = models.EmailField(blank=False)
    birth_date = models.DateField(blank=False)
    sex = models.CharField(blank=False)
    status = models.CharField(blank=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

src/contactsapp/forms.py
from django import forms
from .models import Contact


class ContactForm(forms.ModelForm):
    first_name = forms.CharField(required=True)
    last_name = forms.CharField(required=True)
    address = forms.CharField(required=True)
    phone_number = forms.CharField(required=True)
    email = forms.EmailField(required=True)
    birth_date = forms.DateField(required=True,
                                 widget=forms.DateInput(format='%Y-%m-%d', attrs={'placeholder': 'year-mount-day'}))
    sex = forms.ChoiceField(required=True, choices=(("male", "male"), ("female", "female")))
    status = forms.ChoiceField(required=True, choices=(
        ("family", "family"), ("friend", "friend"), ("partner", "partner"), ("colleague", "colleague"),
        ("other", "other")))

    class Meta:
        model = Contact
        fields = ['first_name', 'last_name', 'address', 'phone_number', 'email', 'address', 'birth_date', 'sex',
                  'status']


class SendEmailForm(forms.ModelForm):
    coppy_to = forms.CharField(max_length=100,
                               required=True,
                               widget=forms.TextInput(attrs={'class': 'form-control'}))

    theme = forms.CharField(max_length=200,
                            required=True,
                            widget=forms.TextInput(attrs={'class': 'form-control'}))

    text = forms.CharField(max_length=2400,
                           required=True,
                           widget=forms.Textarea(attrs={'class': 'form-control'}))

    attachment = forms.FileField(
        required=False,
        widget=forms.ClearableFileInput(attrs={'class': 'form-select'})
    )

    class Meta:
        model = Contact
        fields = ['coppy_to', 'theme', 'text', 'attachment']

src/contactsapp/views.py
from datetime import date, timedelta
from pathlib import Path

from django.shortcuts import render
from django.utils import timezone
from django.shortcuts import render, redirect, get_object_or_404, HttpResponse
from django.contrib.auth.decorators import login_required
from django.db import models
from django.http import HttpResponse
from .models import Contact

from .forms import SendEmailForm, ContactForm
from .models import Contact
import environ
import os
import smtplib
import ssl
from email.mime.base import MIMEBase
from email.mime.image import MIMEImage
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

from django.core.files.uploadedfile import InMemoryUploadedFile
from django.core.mail import EmailMessage
from django.core.paginator import Paginator
from django.shortcuts import render, redirect, get_object_or_404
from django.db.models import Q
from django.views import View

BASE_DIR = Path(__file__).resolve().parent.parent
env = environ.Env()

environ.Env.read_env(BASE_DIR / ".env")
# print(f'{BASE_DIR} ~~ YOUR BASE_DIR')

# /Users/ekaterina/Documents/GitHub/Personal-Assistant-Django
Secret_Key = env("SECRET_KEY")

MetaLogin = env("EMAIL_HOST_USER")
MetaPassword = env("EMAIL_HOST_PASSWORD")


@login_required
def search_contact(request):
    search_query_contact = request.GET.get('search_query', '')
    user_contacts = Contact.objects.filter(user=request.user)
    search_results_contact = user_contacts.filter(
        models.Q(first_name__icontains=search_query_contact) |
        models.Q(last_name__icontains=search_query_contact) |
        models.Q(address__icontains=search_query_contact) |
        models.Q(phone_number__icontains=search_query_contact) |
        models.Q(email__icontains=search_query_contact) |
        models.Q(birth_date__icontains=search_query_contact)
    )
    if search_query_contact == ' ' or search_query_contact == 'all':
        context = {
            'all_results_contact': user_contacts,
            'search_query_contact': search_query_contact
        }
        return render(request, 'contactsapp/search_contact.html', context)
    else:
        context = {
            'search_query_contact': search_query_contact,
            'search_results_contact': search_results_contact
        }
        return render(request, 'contactsapp/search_contact.html', context)


@login_required
def add_contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            contact = form.save(commit=False)
            contact.user = request.user
            contact.save()
            return redirect(to='usersapp:success')
    else:
        form = ContactForm()
    return render(request, 'contactsapp/add_contact.html', context={'form': form})


@login_required
def edit_contact(request, contact_id):
    contact = get_object_or_404(Contact, pk=contact_id, user=request.user)
    if request.method == 'POST':
        form = ContactForm(request.POST, instance=contact)
        if form.is_valid():
            contact = form.save(commit=False)
            contact.user = request.user
            contact.save()
            return redirect(to="contactsapp:detail_contact", contact_id=contact_id)
    else:
        form = ContactForm(instance=contact)
    return render(request, 'contactsapp/edit_contact.html',
                  context={'form': form, 'contact': contact})


@login_required
def detail_contact(request, contact_id):
    contact = get_object_or_404(Contact, pk=contact_id, user=request.user)
    return render(request, 'contactsapp/detail_contact.html', context={'contact': contact})


@login_required
def delete_contact(request, contact_id):
    contact = get_object_or_404(Contact, pk=contact_id, user=request.user)
    if request.method == 'POST':
        contact.delete()
        return redirect(to='usersapp:success')
    return render(request, 'contactsapp/delete_contact.html', context={'contact': contact})


@login_required
def upcoming_birthdays(request):
    if request.method == 'POST':
        days = request.POST.get('days', 0)
        days = int(days) if days else 0
        current_date = date.today()
        end_date = current_date + timedelta(days=days)
        result = []
        contacts = Contact.objects.filter(user=request.user)
        for contact in contacts:
            if contact.birth_date:
                birthday_date = date(year=date.today().year, month=contact.birth_date.month, day=contact.birth_date.day)
                birthday_date_next_year = date(year=date.today().year + 1, month=contact.birth_date.month,
                                               day=contact.birth_date.day)
                if date.today() < birthday_date <= end_date or date.today() < birthday_date_next_year <= end_date:
                    result.append(contact)

    else:
        result = []
    return render(request, 'contactsapp/upcoming_birthdays.html', context={'contacts': result})


class ContactObjectMixin(object):
    model = Contact

    def get_object(self):
        _id = self.kwargs.get('id')
        obj = None
        if _id is not None:
            obj = get_object_or_404(self.model, pk=_id)
        return obj

    def get_id(self):
        return self.kwargs.get("id")


class ContactSendEmail(ContactObjectMixin, View):
    template_name = 'contactsapp/send_email.html'  # DetailView

    def get(self, request, _id=None, *args, **kwargs):
        context = {}
        obj = self.get_object()
        form = SendEmailForm()
        if obj is not None:
            context['object'] = obj

        return render(request, self.template_name, context={"form": form, "object": obj})

    def post(self, request, id=None, *args, **kwargs):
        context = {}
        obj = self.get_object()
        if obj is not None:
            send_email(request, obj)
            context['object'] = None
            return redirect(to='usersapp:success')
        return render(request, self.template_name, context)


def handle_uploaded_file(file: InMemoryUploadedFile):
    try:
        file_name = file.name
        upload_folder_path = "uploads/"
        if not os.path.exists(upload_folder_path):
            os.mkdir(upload_folder_path)
        file_path = upload_folder_path + file_name
        file_contents = file.read()
        with open(file_path, 'wb') as destination:
            destination.write(file_contents)
        return file_path
    except AttributeError:
        return None


def run_send_email(obj: Contact, data: dict, file_path: str):
    user_name = obj.first_name + " " + obj.last_name
    Sender = MetaLogin
    receiver_email = obj.email
    subject = f"Subject: Greetings, dear {user_name}, {data['theme']}"
    message = data['text']
    if file_path:
        attachment_name = os.path.basename(file_path)
        with open(file_path, 'rb') as attachment:
            mail = EmailMessage(subject=subject, body=message, from_email=Sender, to=[receiver_email],
                                cc=[data.get('coppy_to')])
            mail.attach(attachment_name, attachment.read(), data.get('attachment').content_type)
            mail.send()
    else:
        mail = EmailMessage(subject=subject, body=message, from_email=Sender, to=[receiver_email],
                            cc=[data.get('coppy_to')])
        mail.send()


def send_email(request, obj):
    if request.method == 'POST':
        form = SendEmailForm(request.POST, request.FILES)
        if form.is_valid():
            attachment_file: InMemoryUploadedFile = form.cleaned_data['attachment']
            file_path = handle_uploaded_file(attachment_file)
            run_send_email(obj, form.cleaned_data, file_path)
            return render(request, 'usersapp/success.html')
    else:
        form = SendEmailForm()
    return render(request, 'contactsapp/send_email.html', {'form': form})

src/contactsapp/templates/contactsapp/add_contact.html
{% extends "usersapp/base.html" %}

{% block content %}

<div class="container h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-12 col-md-6 col-lg-6 col-xl-5">
            <div class="card" style="border-radius: 15px;">
                <div class="card-body p-5">
                    <h2 class="text-uppercase text-center mb-3">Add Contact</h2>
                    {% if form.errors %}
                    <span class="alert alert-danger" role="alert">{{form.non_field_errors}}</span>
                    {% endif %}
    <form class="container me-2" method="POST" action="{% url 'contactsapp:add_contact' %}">
        {% csrf_token %}
        <div class="form-outline mb-2">
            <label class="form-label">Contact first name*: {{ form.first_name }}</label>
            <span>{{form.errors.first_name}}</span>
        </div>
        <div class="form-outline mb-2">
            <label class="form-label">Contact last name*: {{ form.last_name }}</label>
            <span>{{form.errors.last_name}}</span>
        </div>
        <div class="form-outline mb-2">
            <label class="form-label">Contact address*: {{ form.address }}</label>
            <span>{{form.errors.address}}</span>
        </div>
        <div class="form-outline mb-2">
            <label class="form-label">Contact phone number*: {{ form.phone_number }}</label>
            <span>{{form.errors.phone_number}}</span>
        </div>
        <div class="form-outline mb-2">
            <label class="form-label">Contact email*: {{ form.email }}</label>
            <span>{{form.errors.email}}</span>
        </div>
        <div class="form-outline mb-2">
            <label class="form-label">Contact birthday date*: {{ form.birth_date }}</label>
            <span>{{form.errors.birth_date}}</span>
        </div>
        <div class="form-outline mb-2">
            <select name="sex" id="id_sex">
                <option value="male">male</option>
                <option value="female">female</option>
            </select>
        </div>
        <div class="form-outline mb-2">
            <select name="status" id="id_status">
                <option value="family">family</option>
                <option value="friend">friend</option>
                <option value="partner">partner</option>
                <option value="colleague">colleague</option>
                <option value="other">other</option>
            </select>
        </div>

         <div class="d-flex justify-content-center button-container">
            <button type="submit" class="btn btn-success btn-block btn-lg gradient-custom-5 text-body">Submit</button>
            <button type="reset" class="btn btn-success btn-block btn-lg gradient-custom-5 text-body">Reset</button>
         </div>
    </form>
</div>
</div>
</div>
</div>
</div>
{% endblock %}

src/contactsapp/templates/contactsapp/delete_contact.html
{% extends "usersapp/base.html" %}

{% block content %}
<div class="container h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-12 col-md-6 col-lg-6 col-xl-5">
            <div class="card" style="border-radius: 15px;">
                <div class="card-body p-5">
                    <h2 class="text-uppercase text-center mb-3">Delete Contact</h2>
    <form class="form-control border" method="POST" action="{% url 'contactsapp:delete_contact' contact.id %}">
        {% csrf_token %}
        <div class="d-flex flex-column align-items-center">
            <div class="my-2">Are you sure you want to delete the contact "{{ contact.first_name }}"?</div>
            <button class="btn btn-success btn-block btn-lg gradient-custom-5 text-body col-8" type="submit">Yes</button>
            <button class="btn btn-success btn-block btn-lg gradient-custom-5 text-body col-8"  type="button" onclick="history.back()">No</button>
        </div>
    </form>
</div>
</div>
</div>
</div>
</div>
{% endblock %}

src/contactsapp/templates/contactsapp/detail_contact.html
{% extends "usersapp/base.html" %}

{% block content %}
<style>
.btn-container {
margin-right: 10px;
}
</style>
<div class="container my-1">
    {% if contact %}
            <h4 class="text-center">Results for Contact "{{ contact.first_name }}"</h4>
        <div class="container my-1">
            <div class="form-control d-flex flex-row">
                <div class="flex-fill">
                    <strong>First name:</strong> {{ contact.first_name }}<br>
                    <strong>Last name:</strong> {{ contact.last_name }}<br>
                    <strong>Address:</strong> {{ contact.address }}<br>
                    <strong>Phone Number:</strong> {{ contact.phone_number }}<br>
                    <strong>Email:</strong> {{ contact.email }}<br>
                    <strong>Birthday:</strong> {{ contact.birth_date }}<br>
                    <strong>Sex:</strong> {{ contact.sex }}<br>
                    <strong>Status:</strong> {{ contact.status }}<br>
                </div>
                <div class="d-flex align-items-center">
                    <div class="btn-container">
                        <a class="btn btn-success btn-block btn-lg gradient-custom-5 text-body"  href="{% url 'contactsapp:edit_contact' contact.id %}">Edit Contact</a>
                    </div>
                    <div class="btn-container">
                        <a class="btn btn-success btn-block btn-lg gradient-custom-5 text-body"  href="{% url 'contactsapp:delete_contact' contact.id %}">Delete</a>
                    </div>
                    <div class="btn-container">
                        <a class="btn btn-success btn-block btn-lg gradient-custom-5 text-body"  href="{% url 'contactsapp:send_email' contact.id %}">Send email</a>
                    </div>
                </div>
            </div>
        </div>
        <div align="right"><button class="btn btn-success btn-block btn-lg gradient-custom-5 text-body col-2" type="button" onclick="history.back()">Back</button></div>
    {% endif %}
</div>
{% endblock %}

src/contactsapp/templates/contactsapp/edit_contact.html
{% extends "usersapp/base.html" %}

{% block content %}
<div class="container h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-12 col-md-6 col-lg-6 col-xl-5">
            <div class="card" style="border-radius: 15px;">
                <div class="card-body p-5">
                    <h2 class="text-uppercase text-center mb-3">Edit Contact</h2>
                    {% if form.errors %}
                    <span class="alert alert-danger" role="alert">{{form.non_field_errors}}</span>
                    {% endif %}
    <form class="container me-2" method="POST" action="{% url 'contactsapp:edit_contact' contact.id %}">
        {% csrf_token %}
        <div class="form-outline mb-2">
            <label class="form-label">Edit first name*: {{ form.first_name }}</label>
            <span>{{form.errors.first_name}}</span>
        </div>
        <div class="form-outline mb-2">
            <label class="form-label">Edit last name*: {{ form.last_name }}</label>
            <span>{{form.errors.last_name}}</span>
        </div>
        <div class="form-outline mb-2">
            <label class="form-label">Edit address*: {{ form.address }}</label>
            <span>{{form.errors.address}}</span>
        </div>
        <div class="form-outline mb-2">
            <label class="form-label">Edit phone number*: {{ form.phone_number }}</label>
            <span>{{form.errors.phone_number}}</span>
        </div>
        <div class="form-outline mb-2">
            <label class="form-label">Edit email*: {{ form.email }}</label>
            <span>{{form.errors.email}}</span>
        </div>
        <div class="form-outline mb-2">
            <label class="form-label">Edit birthday date*: {{ form.birth_date }}</label>
            <span>{{form.errors.birth_date}}</span>
        </div>
        <div class="form-outline mb-2">
            <select name="sex" id="id_sex">
                <option value="male">male</option>
                <option value="female">female</option>
            </select>
        </div>
        <div class="form-outline mb-2">
            <select name="status" id="id_status">
                <option value="family">family</option>
                <option value="friend">friend</option>
                <option value="partner">partner</option>
                <option value="colleague">colleague</option>
                <option value="other">other</option>
            </select>
        </div>

         <div class="d-flex justify-content-center button-container">
            <button type="submit" class="btn btn-success btn-block btn-lg gradient-custom-5 text-body">Save</button>
         </div>
    </form>
</div>
</div>
</div>
</div>
</div>
{% endblock %}

src/contactsapp/templates/contactsapp/search_contact.html
{% extends "usersapp/base.html" %}
{% load static %}

{% block content %}
<style>
.custom-container {
    width: 100%;
    margin: 0 auto; /* To center the container horizontally */
    }

.scroll-table-body {
  text-align: center;
 height: 700px;
 overflow-x: center;
 margin-top: 0px;
 margin-bottom: 20px;
 border-bottom: 1px solid #eee;
}
.scroll-table table {
 text-align: center;
 width:100%;
 table-layout: fixed;
 border: 1px solid #ddd;
}
.scroll-table thead th {
 font-weight: bold;
 text-align: center;
 border: none;
 padding: 10px 15px;
 background: #b3b3b3;
 font-size: 14px;
 border-left: 1px solid #ddd;
 border-right: 1px solid #ddd;
}
.scroll-table tbody td {
 text-align: center;
 border-left: 1px solid #ddd;
 border-right: 1px solid #ddd;
 padding: 10px 15px;
 font-size: 14px;
 vertical-align: top;
}
.scroll-table tbody tr:nth-child(even){
 text-align: center;
 background: #b3b3b3;
}
.table {
        text-align: center;
        background-color: #C5F2F3;
        padding: 10px;
        color: #DE00FF;

    }
.my-table {
        text-align: center;
        background-color: #C5F2F3;
        padding: 10px;
        color: #616161;
}
/* Стили для скролла */
::-webkit-scrollbar {
 width: 6px;
}
::-webkit-scrollbar-track {
 box-shadow: inset 0 0 6px rgba(0,0,0,0.3);
}
::-webkit-scrollbar-thumb {
 box-shadow: inset 0 0 6px rgba(0,0,0,0.3);
}

td{
text-align: center;
}

th{
text-align: center;
color: #b3b3b3;
}

</style>
<div class="container my-2">
<!--    <h4 class="text-center">Search by Contact ('all' or space to display all contacts)</h4>-->
    <form class="d-flex" role="search" method="GET" action="{% url 'contactsapp:search_contact' %}">
        <input class="form-control me-4" name="search_query" type="search" placeholder="Search by Contact ('all' or space to display all contacts)" aria-label="Search">
        <button class="btn btn-outline-success" type="submit" style="padding: 5px 10px;">Search</button>
    </form>

{% if search_query_contact %}
<h4 class="text-center">Search results for "{{ search_query_contact }}"</h4>
{% if all_results_contact %}
<div class="custom-container md-10">
    <div class="text-center">
        <div class="scroll-table">
            <table class="table">
                <thead>
                <tr class="tr">
                    <th><strong>First name</strong></th>
                    <th><strong>Last name</strong></th>
                    <th><strong>Email</strong></th>
                    <th><strong>Phone number</strong></th>
                    <th><strong>Birthday</strong></th>
                    <th><strong>Status</strong></th>
                    <th><strong>Sex</strong></th>
                    <th><strong>TG</strong></th>
                    <hr>
                </tr>
                {% for contact in all_results_contact %}
                <tr>
                    <td><a href="{% url 'contactsapp:detail_contact' contact.id %}">{{contact.first_name}}</a></td>
                    <td>{{contact.last_name}}</td>
                    <td><a href="{% url 'contactsapp:send_email' contact.id %}">{{contact.email|truncatechars:15}}</a></td>
                    {% if contact.phone_number != 'None' %}
                    <td>{{contact.phone_number}}</td>
                    {% else %}
                    <td>- - - -</td>
                    {% endif %}
                    <td>{{contact.birth_date}}</td>
                    <td>{{contact.status}}</td>
                    <td>{{contact.sex}}</td>
                    <td>
                        <div class="small text-center button-container">
                            <a href="{% url 'ai_chat_bot:redirect_check' query=contact.id  %}" class="text-center"><i>Virtual
                                Contact Chat</i></a>
                        </div>
                    </td>
                </tr>
                {% endfor %}
                </thead>
                </table>
            </div>
        </div>
    </div>
</div>
{% endif %}
{% if search_results_contact %}
      <div class="custom-container m-10">
    <div class="text-center">
        <div class="scroll-table">
            <table class="table">
                <thead>
                <tr class="tr">
                    <th><strong>first_name</strong></th>
                    <th><strong>last_name</strong></th>
                    <th><strong>email</strong></th>
                    <th><strong>phone_number</strong></th>
                    <th><strong>birth_date</strong></th>
                    <th><strong>status</strong></th>
                    <th><strong>sex</strong></th>
                    <th><strong>TG</strong></th>
                    <hr>
                </tr>
                {% for contact in search_results_contact %}
                <tr>
                    <td><a href="{% url 'contactsapp:detail_contact' contact.id %}">{{contact.first_name}}</a></td>
                    <td>{{contact.last_name}}</td>
                    <td><a href="{% url 'contactsapp:send_email' contact.id %}">{{contact.email|truncatechars:15}}</a></td>
                    {% if contact.phone_number != 'None' %}
                    <td>{{contact.phone_number}}</td>
                    {% else %}
                    <td>- - - -</td>
                    {% endif %}
                    <td>{{contact.birth_date}}</td>
                    <td>{{contact.status}}</td>
                    <td>{{contact.sex}}</td>
                    <td>
                        <div class="small text-center button-container">
                            <a href="{% url 'ai_chat_bot:redirect_check' query=contact.id  %}" class="text-center"><i>Virtual
                                Contact Chat</i></a>
                        </div>
                    </td>
                </tr>
                {% endfor %}
                </thead>
                </table>
            </div>
        </div>
    </div>
{% endif %}
{% endif %}
{% endblock %}

src/contactsapp/templates/contactsapp/upcoming_birthdays.html
{% extends "usersapp/base.html" %}

{% block content %}
<style>
.custom-container {
    width: 100%;
    margin: 0 auto; /* To center the container horizontally */
    }

.scroll-table-body {
  text-align: center;
 height: 700px;
 overflow-x: center;
 margin-top: 0px;
 margin-bottom: 20px;
 border-bottom: 1px solid #eee;
}
.scroll-table table {
 text-align: center;
 width:100%;
 table-layout: fixed;
 border: 1px solid #ddd;
}
.scroll-table thead th {
 font-weight: bold;
 text-align: center;
 border: none;
 padding: 10px 15px;
 background: #b3b3b3;
 font-size: 14px;
 border-left: 1px solid #ddd;
 border-right: 1px solid #ddd;
}
.scroll-table tbody td {
 text-align: center;
 border-left: 1px solid #ddd;
 border-right: 1px solid #ddd;
 padding: 10px 15px;
 font-size: 14px;
 vertical-align: top;
}
.scroll-table tbody tr:nth-child(even){
 text-align: center;
 background: #b3b3b3;
}
.table {
        text-align: center;
        background-color: #C5F2F3;
        padding: 10px;
        color: #DE00FF;

    }
.my-table {
        text-align: center;
        background-color: #C5F2F3;
        padding: 10px;
        color: #616161;
}
/* Стили для скролла */
::-webkit-scrollbar {
 width: 6px;
}
::-webkit-scrollbar-track {
 box-shadow: inset 0 0 6px rgba(0,0,0,0.3);
}
::-webkit-scrollbar-thumb {
 box-shadow: inset 0 0 6px rgba(0,0,0,0.3);
}

td{
text-align: center;
}

th{
text-align: center;
color: #b3b3b3;
}

</style>
<div class="container my-2">
    <h4 class="text-center">Upcoming Birthdays</h4>
    <form class="form-control" method="POST" action="{% url 'contactsapp:upcoming_birthdays' %}">
        {% csrf_token %}
        <div class="d-flex my-1">
            <label class="nav-link fs-6 mt-1 mx-2" for="days">Number of days:</label>
            <input class="me-4" type="number" name="days" id="days" min="1" max="365">
            <button class="btn btn-success btn-block btn-lg gradient-custom-5 text-body" type="submit">Search</button>
        </div>
    </form>
{% if contacts %}
    <h4 class="text-center">Results</h4>
       <div class="custom-container md-10">
    <div class="text-center">
        <div class="scroll-table">
            <table class="table">
                <thead>
                <tr class="tr">
                    <th><strong>First name</strong></th>
                    <th><strong>Last name</strong></th>
                    <th><strong>Email</strong></th>
                    <th><strong>Phone number</strong></th>
                    <th><strong>Birthday</strong></th>
                    <th><strong>Status</strong></th>
                    <th><strong>Sex</strong></th>
                    <th><strong>TG</strong></th>
                    <hr>
                </tr>
                {% for contact in contacts %}
                <tr>
                    <td><a href="{% url 'contactsapp:detail_contact' contact.id %}">{{contact.first_name}}</a></td>
                    <td>{{contact.last_name}}</td>
                    <td><a href="{% url 'contactsapp:send_email' contact.id %}">{{contact.email|truncatechars:15}}</a></td>
                    {% if contact.phone_number != 'None' %}
                    <td>{{contact.phone_number}}</td>
                    {% else %}
                    <td>- - - -</td>
                    {% endif %}
                    <td>{{contact.birth_date}}</td>
                    <td>{{contact.status}}</td>
                    <td>{{contact.sex}}</td>
                    <td>
                        <div class="small text-center button-container">
                            <a href="{% url 'ai_chat_bot:redirect_check' query=contact.id  %}" class="text-center"><i>Virtual
                                Contact Chat</i></a>
                        </div>
                    </td>
                </tr>
                {% endfor %}
                </thead>
                </table>
            </div>
        </div>
    </div>
    {% else %}
        <h4 class="text-center">Results</h4>
    {% endif %}
</div>
{% endblock %}