src/cloud_storageapp/urls.py
from django.urls import path
from . import views


app_name = 'cloud_storageapp'

urlpatterns = [
    path('authorize/', views.dropbox_oauth, name='dropbox_oauth'),
    path('authorized/', views.dropbox_authorized, name='dropbox_authorized'),
    # path('search-files/', views.search_files, name='search_files'),
    path('dropbox-folders/', views.dropbox_folders, name='dropbox_folders'),
    path('upload-file/', views.upload_file, name='upload_file'),
    path('success_upload/', views.success_upload, name='success_upload'),
    path('dropbox-folders/<path:folder_path>/', views.folder_files, name='folder_files'),
    path('download-file/<path:file_path>/', views.download_file, name='download_file'),
    path('remove-folder/<path:folder_path>/', views.remove_folder, name='remove_folder'),
    path('remove-file/<path:file_path>/', views.remove_file, name='remove_file'),
    path('dropbox-folders-docs/<path:folder_path>/', views.folder_files_docs, name='folder_files_docs'),
    path('dropbox-folders-pics/<path:folder_path>/', views.folder_files_images, name='folder_files_images'),
    path('dropbox-folders-video/<path:folder_path>/', views.folder_files_video, name='folder_files_video'),
    path('dropbox-folders-audio/<path:folder_path>/', views.folder_files_audio, name='folder_files_audio'),
]

src/newsapp/urls.py
from django.shortcuts import render

# Create your views here.
from django.urls import path
from . import views

app_name = 'newsapp'

urlpatterns = [
    path('read_news/<str:q>/', views.choice_topic, name="read_news"),
    path('detail_paragraph/<str:q>/', views.paragraph, name="detail_paragraph"),
    ]

src/personal_assistant/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from usersapp.views import root

urlpatterns = [
    path('', root, name='root'),
    path('admin/', admin.site.urls),
    path('users/', include('usersapp.urls')),
    path('bot/', include('ai_chat_bot.urls')),
    path('contacts/', include('contactsapp.urls')),
    path('notes/', include('notesapp.urls')),
    path('news/', include('newsapp.urls')),
    path('cloud_storageapp/', include('cloud_storageapp.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/cloud_storageapp/models.py
from django.db import models

class MyModel(models.Model):
    my_file = models.FileField(upload_to='uploads/')

src/cloud_storageapp/forms.py
import re

from django import forms


class FileUploadForm(forms.Form):
    file = forms.FileField()

    folder = forms.CharField(max_length=30, required=False)

    def clean_custom_folder(self):
        custom_folder = self.cleaned_data['custom_folder']
        if not re.match(r'^[-_.A-Za-z0-9()]+(/[-_.A-Za-z0-9()]+)*$', custom_folder):
            raise forms.ValidationError(
                "Invalid folder name. Please use alphanumeric characters, hyphens, underscores, dots, and parentheses.")
        return custom_folder

src/cloud_storageapp/views.py
import json
import os
from pathlib import Path
from dropbox.exceptions import AuthError
import requests
from django.http import JsonResponse, FileResponse, HttpResponseNotFound, HttpResponseRedirect, HttpResponse
from django.shortcuts import render, redirect
import environ
import dropbox
from .forms import FileUploadForm

import datetime
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
env = environ.Env()

environ.Env.read_env(BASE_DIR / ".env")
# print(f'{BASE_DIR} ~~ YOUR BASE_DIR')

# /Users/ekaterina/Documents/GitHub/Personal-Assistant-Django
Secret_Key = env("SECRET_KEY")
# Create your views here.

DROPBOX_APP_KEY = env("DROPBOX_APP_KEY")
DROPBOX_APP_SECRET = env("DROPBOX_APP_SECRET")
# DROPBOX_OAUTH2_REFRESH_TOKEN = env("DROPBOX_OAUTH2_REFRESH_TOKEN")
REDIRECT_URL = 'http://127.0.0.1:8000/cloud_storageapp/'

def dropbox_oauth(request):
    print('Auth Started !!!!!!!!!!!')
    return redirect(f'https://www.dropbox.com/oauth2/authorize?client_id={DROPBOX_APP_KEY}&redirect_uri={REDIRECT_URL}authorized&response_type=code')


def dropbox_authorized(request):
    try:
        code = request.GET["code"]
        print(f"Code: {code}")
    except KeyError:
        return JsonResponse({"error": "Authorization code not found in the request."}, status=400)
    data = requests.post('https://api.dropboxapi.com/oauth2/token', {
        "code": code,
        "grant_type": "authorization_code",
        "redirect_uri": f"{REDIRECT_URL}authorized",
    }, auth=(DROPBOX_APP_KEY, DROPBOX_APP_SECRET))
    request.session["DROPBOX_ACCESS_TOKEN"] = data.json()["access_token"]
    with open('OAuth_token.json', 'w') as file:
        json.dump({"datetime":datetime.datetime.now().strftime("%Y-%m-%d %H:%M"), "token": data.json()["access_token"]}, file, indent=4, ensure_ascii=False)

    return redirect(to="cloud_storageapp:dropbox_folders")







# """query for search!"""
# def search_files(request, claudinary=None):
#     if request.method == "POST":
#         data=requests.post("https://api.dropboxapi.com/2/files/search_v2", headers={
#             "Authorization": f"Bearer {request.session['DROPBOX_ACCESS_TOKEN']}",
#         }, json={
#             "query": "cc"
#         })
#
#         results = []
#         for f in data.json()["matches"]:
#             id = f["metadata"]["metadata"]["id"]
#             data = requests.post("https://api.dropboxapi.com/2/files/get_preview", headers={
#                 "Authorization": f"Bearer {request.session['DROPBOX_ACCESS_TOKEN']}",
#                  "Dropbox-API-Arg": json.dumps({"path": id})}, stream=True)
#             print(data.text)
#             r = claudinary.uploader.upload(data.content)
#             img_url = r["secure_url"]
#             return JsonResponse(data.json())
#     else:
#         return render(request, "cloud_storageapp/search.html")


def get_access_token():
    with open('OAuth_token.json', 'r') as file:
        data =  json.load(file)
        date = data.get('datetime')
        date_dt_obj = datetime.datetime.strptime(date, "%Y-%m-%d %H:%M")
        curent_time = datetime.datetime.now()
        delta = ((curent_time - date_dt_obj).total_seconds()) / 60 / 60
        print(delta)
        if delta > 3:
            return None
        token = data.get('token')
        print(date, token)
        return token


def get_access_dbx(request):
    dbx = None
    try:
        access_token = get_access_token()
        if access_token:
            dbx = dropbox.Dropbox(access_token)
        else:
            print("Try refresh!!!!!!!!!!!!")
            return redirect(to="cloud_storageapp:dropbox_oauth")
    except Exception as err:
        print(f"My ERROR !!!!! ::: {err}")

    return dbx



def dropbox_folders(request):
    # try:
    #     access_token = get_access_token()
    #     if access_token:
    #         dbx = dropbox.Dropbox(access_token)
    #     else:
    #         print("Try refresh!!!!!!!!!!!!")
    #         return redirect(to="cloud_storageapp:dropbox_oauth")
    #         print("Try refresh   Ok Ok OK OK ")
    # except Exception as err:
    #     print(f"My ERROR !!!!! ::: {err}")

    dbx = get_access_dbx(request)
    if isinstance(dbx, (HttpResponseRedirect, type(None))):
        print(f'ISTANCE ::::::::::::::: {dbx}')
        return redirect(to='cloud_storageapp:dropbox_oauth')
    # List all files in the root directory
    folders = []
    for entry in dbx.files_list_folder('', recursive=True).entries:
        if isinstance(entry, dropbox.files.FolderMetadata):
            folders.append(entry)

    context = {'folders': folders}
    return render(request, 'dropbox_folders.html', context)



def folder_files(request, folder_path):
    print(str(folder_path).strip('/'))
    dbx = get_access_dbx(request)
    if isinstance(dbx, (HttpResponseRedirect, type(None))):
        print(f'ISTANCE ::::::::::::::: {dbx}')
        return redirect(to='cloud_storageapp:dropbox_oauth')
    files = []
    try:
        result = dbx.files_list_folder(folder_path)
        for entry in result.entries:
            if isinstance(entry, dropbox.files.FileMetadata):
                files.append(entry)
    except dropbox.exceptions.ApiError as e:
        if e.error.is_path() and \
                e.user_message_text.startswith("not_folder/"):
            # The provided path is not a folder path, handle the error as needed
            pass
        else:
            raise

    context = {'files': files, 'folder_path': folder_path}
    return render(request, 'folder_files.html', context)



    # for entry in dbx.files_list_folder(folder_path).entries:
    #     if isinstance(entry, dropbox.files.FileMetadata):
    #         files.append(entry)
    #
    # context = {'files': files, 'folder_path': folder_path}
    # return render(request, 'folder_files.html', context)



def success_upload(request):
    return render(request, 'upload_success.html', {})



def upload_file(request):
    if request.method == 'POST':
        form = FileUploadForm(request.POST, request.FILES)
        if form.is_valid():
            # Replace 'YOUR_DROPBOX_ACCESS_TOKEN' with your Dropbox access token
            dbx = get_access_dbx(request)
            if isinstance(dbx, (HttpResponseRedirect, type(None))):
                print(f'ISTANCE ::::::::::::::: {dbx}')
                return redirect(to='cloud_storageapp:dropbox_oauth')
            folder = form.cleaned_data['folder'].replace(' ', '_')
            print(f"FOLDER::::::  ::  : :: : {folder}")

            file = request.FILES['file']
            print(f"FILE CLEAN NAME :  {file.name.replace(' ', '_')}")
            clean_file_name = file.name.replace(' ', '_')
            file_path = f'/{folder}/{clean_file_name}' if folder else f'/unknown/{clean_file_name}'
            print(f"FILE PASS II : {file_path}")
            dbx.files_upload(file.read(), file_path)

            # Redirect to a success page or display a success message
            return redirect(to='cloud_storageapp:success_upload')

    else:
        form = FileUploadForm()

    return render(request, 'upload_file.html', {'form': form})



# dbx.files_download(db_query_file, rev=None)

def download_file(request, file_path):

    file_full_path = 'cloud_storageapp/download-file/'+file_path

    # while '//' in file_full_path:
    #     file_full_path = file_full_path.replace('//', '/')
    print(f'FILE PASSSSSSSSSS    {file_full_path}')
    dbx = get_access_dbx(request)
    if isinstance(dbx, (HttpResponseRedirect, type(None))):
        print(f'ISTANCE ::::::::::::::: {dbx}')
        return redirect(to='cloud_storageapp:dropbox_oauth')
    # file = request.FILES['file']

    try:
        metadata, response = dbx.files_download(file_path, rev=None)

    except dropbox.exceptions.ApiError as e:
        return HttpResponseNotFound("File not found. Exeption from except!")

    file_content = response.content
    # content_type = metadata.mime_type
    content_type = response.headers.get('Content-Type')
    print(f"CONTENT TYPE::::::::   {content_type}")
    response = HttpResponse(file_content, content_type=content_type)
    response['Content-Disposition'] = f'attachment; filename="{os.path.basename(file_full_path)}"'
    return response



def remove_folder(request, folder_path):

    dbx = get_access_dbx(request)
    if isinstance(dbx, (HttpResponseRedirect, type(None))):
        print(f'ISTANCE ::::::::::::::: {dbx}')
        return redirect(to='cloud_storageapp:dropbox_oauth')

    folder_path = folder_path.replace('%20', ' ')
    dbx.files_delete_v2(folder_path)
    print('files was removed')
    return redirect(to='cloud_storageapp:dropbox_folders')


def remove_file(request, file_path):
    print(file_path)
    folder = file_path.split('/')[1]
    print(folder)
    dbx = get_access_dbx(request)
    file_path = file_path.replace('%2520', ' ')
    file_path = file_path.replace('%20', ' ')

    if isinstance(dbx, (HttpResponseRedirect, type(None))):
        print(f'ISTANCE ::::::::::::::: {dbx}')
        return redirect(to='cloud_storageapp:dropbox_oauth')

    dbx.files_delete_v2(file_path)
    print('files was removed')
    return redirect(to='cloud_storageapp:folder_files', folder_path=f"/{folder}")


def folder_files_docs(request, folder_path):
    print(str(folder_path).strip('/'))
    dbx = get_access_dbx(request)
    if isinstance(dbx, (HttpResponseRedirect, type(None))):
        print(f'ISTANCE ::::::::::::::: {dbx}')
        return redirect(to='cloud_storageapp:dropbox_oauth')
    files = []
    folders = []

    try:
        result = dbx.files_list_folder(folder_path)
        for entry in result.entries:
            if isinstance(entry, dropbox.files.FileMetadata):
                _, file_extension = os.path.splitext(entry.name)
                if file_extension.lower() in ['.docx', '.doc','.pdf','.xls','.xlsx','.ppt','.pptx','.xps','.dot','.wbk','.docm','.txt','.rtf','.log']:

src/cloud_storageapp/templates/dropbox_files.html
{% extends 'usersapp/base.html' %}
{% load static %}
{% block content %}
<link rel="stylesheet" type="text/css" href="/path/to/styles.css">
<div class="container h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-11 col-md-8 col-lg-8 col-xl-10">
            <div class="card" style="border-radius: 15px;">
                <div class="card-body p-5">
                    <h2 class="text-uppercase text-center mb-3">File Uploaded Successfully</h2>
                    <ul>
                        {% for folder in folders %}
                        <li><a href="{% url 'cloud_storageapp:folder_files' folder_path=folder.path_display %}">{{folder.name}}</a>
                            <form action="{% url 'cloud_storageapp:remove_folder' folder_path=folder.path_display|urlencode %}"
                                  method="post">
                                {% csrf_token %}
                                <button type="submit">Remove folder</button>
                            </form>
                        </li>
                        {% endfor %}
                    </ul>
                </div></div></div></div></div>
{% endblock %}
    <ul>
        {% for file in files %}
            <li>{{ file.name }}</li>
        {% endfor %}
    </ul>
</body>
</html>

src/cloud_storageapp/templates/dropbox_folders.html
{% extends 'usersapp/base.html' %}
{% load static %}
{% block content %}
<div class="container h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-12 col-md-8 col-lg-6 col-xl-8">
            <div class="card" style="border-radius: 15px;">
                <div class="card-body d-flex flex-column align-items-center">
                    <h2 class="text-uppercase text-center mb-3">Your Folders</h2>
                    <ul>
                        {% for folder in folders %}
                        <li><a href="{% url 'cloud_storageapp:folder_files' folder_path=folder.path_display %}" >{{folder.name}}</a>
                            <form action="{% url 'cloud_storageapp:remove_folder' folder_path=folder.path_display|urlencode %}"
                                  method="post">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-success btn-block btn-lg gradient-custom-5 text-body smaller-button" style="font-size: 14px; padding: 6px 12px; width: 150px;">Remove folder</button>
                            </form>
                        </li>
                        {% endfor %}
                    </ul>
                    <input type="button" value="Go back!" onclick="history.back()">
                </div></div></div></div></div>

{% endblock %}

src/cloud_storageapp/templates/folder_files.html
{% extends 'usersapp/base.html' %}
{% load static %}
{% block content %}
<link rel="stylesheet" type="text/css" href="/path/to/styles.css">
<div class="container h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-12 col-md-8 col-lg-6 col-xl-8">
            <div class="card" style="border-radius: 15px;">
                <div class="card-body d-flex flex-column align-items-center">

                    <h2 class="text-uppercase text-center mb-3">Your files</h2>

                     <ul>
                        <li><a href="{% url 'cloud_storageapp:folder_files_images' folder_path %}" class="btn btn-primary btn-block btn-lg gradient-custom-4 text-body smaller-button" style="font-size: 14px; padding: 6px 12px; width: 150px;">Pictures</a></li>
                         <li><a href="{% url 'cloud_storageapp:folder_files_video' folder_path %}" class="btn btn-primary btn-block btn-lg gradient-custom-4 text-body smaller-button" style="font-size: 14px; padding: 6px 12px; width: 150px;">Video</a></li>
                        <li><a href="{% url 'cloud_storageapp:folder_files_docs' folder_path %}" class="btn btn-primary btn-block btn-lg gradient-custom-4 text-body smaller-button" style="font-size: 14px; padding: 6px 12px; width: 150px;">Docs</a></li>
                        <li><a href="{% url 'cloud_storageapp:folder_files_audio' folder_path %}" class="btn btn-primary btn-block btn-lg gradient-custom-4 text-body smaller-button" style="font-size: 14px; padding: 6px 12px; width: 150px;">Media</a></li>
                    </ul>
                    <ul>

                        {% for file in files %}
                        <li><a href="{% url 'cloud_storageapp:download_file' file_path=file.path_display|urlencode %}">{{file.name}}</a></li>
                        <form action="{% url 'cloud_storageapp:remove_file' file_path=file.path_display|urlencode %}"
                              method="post">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-success btn-block btn-lg gradient-custom-5 text-body smaller-button" style="font-size: 14px; padding: 6px 12px; width: 150px;">Remove file</button>
                        </form>
                        {% endfor %}

                    </ul>
                    <input type="button" value="Go back!" onclick="history.back()">

                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

</body>
</html>

src/cloud_storageapp/templates/folder_files_audio.html
{% extends 'usersapp/base.html' %}
{% load static %}
{% block content %}
<link rel="stylesheet" type="text/css" href="/path/to/styles.css">
<div class="container h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-12 col-md-8 col-lg-6 col-xl-8">
            <div class="card" style="border-radius: 15px;">
                <div class="card-body d-flex flex-column align-items-center">
                    <h2 class="text-uppercase text-center mb-3">Your files</h2>
                    <ul>
                        {% for file in files %}
                        <li><a href="{% url 'cloud_storageapp:download_file' file_path=file.path_display|urlencode %}">{{file.name}}</a></li>
                        <form action="{% url 'cloud_storageapp:remove_file' file_path=file.path_display|urlencode %}"
                              method="post">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-success btn-block btn-lg gradient-custom-5 text-body smaller-button" style="font-size: 14px; padding: 6px 12px; width: 150px;">Remove file</button>

                        </form>
                        {% endfor %}
                    </ul>
                    <input type="button" value="Go back!" onclick="history.back()">
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

</body>
</html>

src/cloud_storageapp/templates/folder_files_docs.html
{% extends 'usersapp/base.html' %}
{% load static %}
{% block content %}
<link rel="stylesheet" type="text/css" href="/path/to/styles.css">
<div class="container h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-12 col-md-8 col-lg-6 col-xl-8">
            <div class="card" style="border-radius: 15px;">
                <div class="card-body d-flex flex-column align-items-center">
                    <h2 class="text-uppercase text-center mb-3">Your files</h2>
                    <ul>
                        {% for file in files %}
                        <li><a href="{% url 'cloud_storageapp:download_file' file_path=file.path_display|urlencode %}">{{file.name}}</a></li>
                        <form action="{% url 'cloud_storageapp:remove_file' file_path=file.path_display|urlencode %}"
                              method="post">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-success btn-block btn-lg gradient-custom-5 text-body smaller-button" style="font-size: 14px; padding: 6px 12px; width: 150px;">Remove file</button>

                        </form>
                        {% endfor %}
                    </ul>
                    <input type="button" value="Go back!" onclick="history.back()">
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

</body>
</html>

src/cloud_storageapp/templates/folder_files_images.html
{% extends 'usersapp/base.html' %}
{% load static %}
{% block content %}
<link rel="stylesheet" type="text/css" href="/path/to/styles.css">
<div class="container h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-12 col-md-8 col-lg-6 col-xl-8">
            <div class="card" style="border-radius: 15px;">
                <div class="card-body d-flex flex-column align-items-center">
                    <h2 class="text-uppercase text-center mb-3">Your files</h2>
                    <ul>
                        {% for file in files %}
                        <li><a href="{% url 'cloud_storageapp:download_file' file_path=file.path_display|urlencode %}">{{file.name}}</a></li>
                        <form action="{% url 'cloud_storageapp:remove_file' file_path=file.path_display|urlencode %}"
                              method="post">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-success btn-block btn-lg gradient-custom-5 text-body smaller-button" style="font-size: 14px; padding: 6px 12px; width: 150px;">Remove file</button>

                        </form>
                        {% endfor %}
                    </ul>
                    <input type="button" value="Go back!" onclick="history.back()">
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

</body>
</html>

src/cloud_storageapp/templates/folder_files_video.html
{% extends 'usersapp/base.html' %}
{% load static %}
{% block content %}
<link rel="stylesheet" type="text/css" href="/path/to/styles.css">
<div class="container h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-12 col-md-8 col-lg-6 col-xl-8">
            <div class="card" style="border-radius: 15px;">
                <div class="card-body d-flex flex-column align-items-center">
                    <h2 class="text-uppercase text-center mb-3">Your files</h2>
                    <ul>
                        {% for file in files %}
                        <li><a href="{% url 'cloud_storageapp:download_file' file_path=file.path_display|urlencode %}">{{file.name}}</a></li>
                        <form action="{% url 'cloud_storageapp:remove_file' file_path=file.path_display|urlencode %}"
                              method="post">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-success btn-block btn-lg gradient-custom-5 text-body smaller-button" style="font-size: 14px; padding: 6px 12px; width: 150px;">Remove file</button>

                        </form>
                        {% endfor %}
                    </ul>
                    <input type="button" value="Go back!" onclick="history.back()">
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

</body>
</html>

src/cloud_storageapp/templates/upload_file.html
{% extends 'usersapp/base.html' %}
{% load static %}
{% block content %}

<div class="container h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-12 col-md-6 col-lg-6 col-xl-5">
            <div class="card" style="border-radius: 15px;">
                <div class="card-body p-5">
                    <h2 class="text-uppercase text-center mb-3">Upload a File</h2>
                    {% if form.errors %}
                    <span class="alert alert-danger" role="alert">{{form.non_field_errors}}</span>
                    {% endif %}
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <input type="file" name="file">
                        <input type="text" name="folder">
                        <button type="submit">Upload</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

src/cloud_storageapp/templates/upload_success.html
{% extends 'usersapp/base.html' %}
{% load static %}
{% block content %}
<div class="container h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-12 col-md-6 col-lg-6 col-xl-5">
            <div class="card" style="border-radius: 15px;">
                <div class="card-body p-5">
                    <h2 class="text-uppercase text-center mb-3">File Uploaded Successfully</h2>

                    <p>Your file has been uploaded to Dropbox successfully.</p>
                    <a href="{% url 'cloud_storageapp:dropbox_folders' %}"
                       class="btn btn-success btn-block btn-lg gradient-custom-5 text-body">View all Folders</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}