src/newsapp/urls.py
from django.shortcuts import render

# Create your views here.
from django.urls import path
from . import views

app_name = 'newsapp'

urlpatterns = [
    path('read_news/<str:q>/', views.choice_topic, name="read_news"),
    path('detail_paragraph/<str:q>/', views.paragraph, name="detail_paragraph"),
    ]

src/personal_assistant/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from usersapp.views import root

urlpatterns = [
    path('', root, name='root'),
    path('admin/', admin.site.urls),
    path('users/', include('usersapp.urls')),
    path('bot/', include('ai_chat_bot.urls')),
    path('contacts/', include('contactsapp.urls')),
    path('notes/', include('notesapp.urls')),
    path('news/', include('newsapp.urls')),
    path('cloud_storageapp/', include('cloud_storageapp.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/usersapp/urls.py
from .views import main, login_user, create_user_profile, logout_user, ResetPasswordView, terms, activate, success
from django.contrib.auth.views import PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static


app_name = 'usersapp'

urlpatterns = [
    path('', main, name='main'),

    path('terms/', terms, name='terms'),
    path('login/', login_user, name='login_user'),
    path('signup/', create_user_profile, name='create_user_profile'),
    path('logout/', logout_user, name='logout_user'),
    path('success/', success, name='success'),
    path('reset-password/', ResetPasswordView.as_view(), name='password_reset'),
    path('reset-password/done/', PasswordResetDoneView.as_view(template_name='usersapp/password_reset_done.html'),
         name='password_reset_done'),
    path('reset-password/confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='usersapp/password_reset_confirm.html',
                                          success_url='/users/reset-password/complete/'),
         name='password_reset_confirm'),
    path('reset-password/complete/',
         PasswordResetCompleteView.as_view(template_name='usersapp/password_reset_complete.html'),
         name='password_reset_complete'),
    path('activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/',
            activate, name='activate'),
]

urlpatterns += staticfiles_urlpatterns()


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/usersapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class CustomUser(AbstractUser):
    ROLE_CHOICES = (
        ('admin', 'Admin'),
        ('user', 'User'),
        ('manager', 'Manager'),
        ('developer', 'Developer'),
        ('support', 'Support'),
    )

    role = models.CharField(max_length=120, choices=ROLE_CHOICES, default='user')
    telegram_id = models.CharField(max_length=120, blank=True)

    def __str__(self):
        return f' User - {self.username} has a role:  {self.role}'

src/usersapp/forms.py
from django import forms
from .models import CustomUser
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm


class CustomUserRegisterForm(UserCreationForm):
    email = forms.EmailField(max_length=100,
                             required=True,
                             widget=forms.EmailInput(attrs={'class': 'form-control'}))

    username = forms.CharField(max_length=20,
                               required=True,
                               widget=forms.TextInput(attrs={'class': 'form-control'}))

    first_name = forms.CharField(max_length=100,
                               required=False,
                               widget=forms.TextInput(attrs={'class': 'form-control'}))

    last_name = forms.CharField(max_length=100,
                               required=False,
                               widget=forms.TextInput(attrs={'class': 'form-control'}))

    password1 = forms.CharField(max_length=16,
                                required=True,
                                widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    password2 = forms.CharField(max_length=16,
                                required=True,
                                widget=forms.PasswordInput(attrs={'class': 'form-control'}))

    class Meta:
        model = CustomUser
        fields = ['email', 'username', 'first_name', 'last_name', 'password1', 'password2']


class LoginForm(AuthenticationForm):
    # email = forms.EmailField(max_length=100,
    #                          required=True,
    #                          widget=forms.EmailInput(attrs={'class': 'form-control'}))

    username = forms.CharField(max_length=20,
                               required=True,
                               widget=forms.TextInput(attrs={'class': 'form-control'}))

    password = forms.CharField(max_length=16,
                               required=True,
                               widget=forms.PasswordInput(attrs={'class': 'form-control'}))

    class Meta:
        model = CustomUser
        fields = ['username', 'password']

src/usersapp/views.py
from django.core.mail import EmailMessage

from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render, redirect, HttpResponse
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.template.loader import render_to_string
from django.utils.encoding import force_bytes, force_str
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from . import forms
from django.contrib.auth.views import PasswordResetView
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.contrib.sites.shortcuts import get_current_site

from .tokens import account_activation_token

from .models import CustomUser


def main(request):
    return render(request=request, template_name='usersapp/index.html', context={})

def root(request):
    return render(request=request, template_name='usersapp/main.html', context={})

def terms(request):
    return render(request=request, template_name='usersapp/terms.html', context={})

def create_user_profile(request):
    if request.user.is_authenticated:
        return redirect('usersapp:main')

    if request.method == 'POST':
        form = forms.CustomUserRegisterForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.save()
            # form.save()
            current_site = get_current_site(request)
            mail_subject = 'Activation link has been sent to your email id'
            message = render_to_string('usersapp/acc_active_email.html', {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': account_activation_token.make_token(user),
            })
            print(message)
            to_email = form.cleaned_data.get('email')
            print(to_email)
            email = EmailMessage(
                mail_subject, message, to=[to_email]
            )
            print("Email Sending .....")
            email.send()
            return redirect('usersapp:login_user')

        else:
            print("Form is not valid!!!!!!!!!!!")
            form = forms.CustomUserRegisterForm()
            return render(request, 'usersapp/signup.html', context={"form": form})
    print("Method GET !!!!!!!!")
    form = forms.CustomUserRegisterForm()
    return render(request, 'usersapp/signup.html', context={"form": form})


def activate(request, uidb64, token):

    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = CustomUser.objects.get(pk=uid)
        print("Run Activate ............")
        print(user.pk)
    except(TypeError, ValueError, OverflowError):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        print("User Not NONE !!!!!!!!!")
        user.is_active = True
        user.save()
        return redirect('usersapp:login_user')

    else:
        print("User is NONE !!!!!!!!!!!!!!")
        return redirect('usersapp:create_user_profile')


def login_user(request):
    if request.user.is_authenticated:
        return redirect(to='usersapp:main')

    if request.method == 'POST':
        print('I\'m in POST')
        user = authenticate(username=request.POST['username'], password=request.POST['password'])
        print(user)
        if user is None:
            print('I\'m in POST but user is NONE ')
            messages.error(request, 'Username or password didn\'t match')
            return redirect(to='usersapp:login_user')

        login(request, user)
        print("You was Logged IN !!!!!!!!!!!!!!!")
        return redirect(to='usersapp:main')

    form = forms.LoginForm()
    return render(request, 'usersapp/login.html', context={"form": form})


@login_required
def logout_user(request):
    logout(request)
    return redirect(to='usersapp:login_user')


@login_required
def success(request):
    return render(request, 'usersapp/success.html')


class ResetPasswordView(SuccessMessageMixin, PasswordResetView):
    template_name = 'usersapp/password_reset.html'
    email_template_name = 'usersapp/password_reset_email.html'
    html_email_template_name = 'usersapp/password_reset_email.html'
    success_url = reverse_lazy('usersapp:password_reset_done')
    success_message = "An email with instructions to reset your password has been sent to %(email)s."
    subject_template_name = 'usersapp/password_reset_subject.txt'

src/usersapp/templates/usersapp/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css"
          rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <link rel="stylesheet" href="https://unpkg.com/@picocss/pico@latest/css/pico.min.css"/>
     {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'usersapp/css/style.css' %}">



    <title> Django Project! </title>
</head>
<body>
{% if user.is_authenticated %}
{% include 'usersapp/navbar.html' %}
{% endif %}
<section class="vh-100 bg-image"

         style="background-image: url('https://mdbcdn.b-cdn.net/img/Photos/new-templates/search-box/img4.webp');">

    <div class="mask d-flex align-items-center h-100 gradient-custom-3">

{% block content %}

{% endblock %}
</div>
</section>

{% include 'usersapp/footer.html' %}

</body>
</html>

src/usersapp/templates/usersapp/baze.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css"
          rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <link rel="stylesheet" href="https://unpkg.com/@picocss/pico@latest/css/pico.min.css"/>
     {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'usersapp/css/style.css' %}">

    <title> Django Project! </title>
</head>
<body>

{% block content %}

{% endblock %}



</body>
</html>

src/usersapp/templates/usersapp/footer.html
<style>
.li-padding {
padding: 30px;
}
</style>

<footer class="py-3 my-4">
  <p class="text-center text-muted">Created by:</p>
  <ul class="nav justify-content-center border-bottom pb-3 mb-3">
    <li class="nav-item mb-1 li-padding"><a href="https://github.com/osandrey" class="nav-link px-2 text-muted">Andriy Osypenko</a></li>
    <li class="nav-item mb-1 li-padding"><a href="https://github.com/VadimTrubay" class="nav-link px-2 text-muted">Vadim Trubay</a></li>
    <li class="nav-item mb-1 li-padding"><a href="https://github.com/Balanin" class="nav-link px-2 text-muted">Volodymyr Balan</a></li>
    <li class="nav-item mb-1 li-padding"><a href="https://github.com/KarynaSam" class="nav-link px-2 text-muted">Samoylenko Karyna</a></li>
  </ul>
  <p class="text-center text-muted">© {% now "Y" %} Personal Assistant Django</p>
</footer>

src/usersapp/templates/usersapp/index.html
{% extends 'usersapp/base.html' %}
{% load static %}

{% block content %}

{% endblock %}

src/usersapp/templates/usersapp/login.html
{% extends 'usersapp/base.html' %}
{% load static %}
{% block content %}
        <div class="container h-100">
            <div class="row d-flex justify-content-center align-items-center h-100">
                <div class="col-12 col-md-6 col-lg-6 col-xl-5">
                    <div class="card" style="border-radius: 15px;">
                        <div class="card-body p-5">
                            <h2 class="text-uppercase text-center mb-3">Login to your account</h2>
                            {% if form.errors %}
                            <span class="alert alert-danger" role="alert">{{form.non_field_errors}}</span>
                            {% endif %}




                            <form method="post" action="{% url 'usersapp:login_user' %}">
                                {% csrf_token %}
                                <div class="form-outline mb-2">
                                    <!--                                    <input type="email" id="form3Example3cg" class="form-control form-control-lg"/>-->
                                    <label class="form-label">Your Username: {{ form.username }}</label>
                                    <span>{{form.errors.username}}</span>
                                </div>


                                <div class="form-outline mb-2">
                                    <!--                                    <input type="text" id="form3Example6cg" class="form-control form-control-lg"/>-->
                                    <label class="form-label">Your Password: {{ form.password }}</label>
                                    <span>{{form.errors.password}}</span>
                                </div>


                                <div class="d-flex justify-content-center button-container">
                                    <button type="submit" class="btn btn-success btn-block btn-lg gradient-custom-5 text-body">Submit</button>
                                    <button type="reset" class="btn btn-success btn-block btn-lg gradient-custom-5 text-body">Reset</button></div>
                                <div class="small text-center button-container">
                                        <a href="{% url 'usersapp:password_reset' %}" class="text-center"><i>Forgot
                                            Password?</i></a></div>
                                    <div class="small text-center button-container"><a href="{% url 'usersapp:create_user_profile' %}" class="text-center"><i>Don't have account yet?</i></a>
                                        </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
{% endblock %}

src/usersapp/templates/usersapp/logout.html
{% extends "usersapp/base.html" %}

{% block content %}

<h1>Thank you for using our services.</h1>
<h2>Thank you for using our services.</h2>
<h3>Thank you for using our services.</h3>
<h4>Thank you for using our services.</h4>
<h5>Thank you for using our services.</h5>
<h6>Thank you for using our services.</h6>

{% endblock %}

src/usersapp/templates/usersapp/password_reset_complete.html
{% extends "usersapp/base.html" %}

{% block content %}

<div class="container h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-12 col-md-6 col-lg-6 col-xl-5">
            <div class="card" style="border-radius: 15px;">
                <div class="card-body p-5">
                    <h2 class="text-uppercase text-center mb-3">Password reset complete!</h2>
                    <div class="d-flex justify-content-center button-container">
                        <a href="{% url 'usersapp:login_user' %}" class="btn btn-success btn-block btn-lg gradient-custom-5 text-body">
                            Sign In to your account
                        </a>
                </div></div></div></div></div>


{% endblock %}

src/usersapp/templates/usersapp/password_reset_done.html
{% extends "usersapp/base.html" %}

{% block content %}

<div class="container h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-12 col-md-6 col-lg-6 col-xl-5">
            <div class="card" style="border-radius: 15px;">
                <div class="card-body p-5">
                    <h2 class="text-uppercase text-center mb-3">Password reset request sen</h2>
                    <p>We've emailed you with instructions on how to reset your password!</p>
                </div></div></div></div></div>


{% endblock %}

src/usersapp/templates/usersapp/password_reset_email.html
{% autoescape off %}
<body>
<p>Hi {{ user.username }},</p>
<p>You requested a password reset for your account. Please follow this link to set a new password:</p>
<p>
    <a href="{{ protocol }}://{{ domain }}{% url 'usersapp:password_reset_confirm' uidb64=uid token=token %}">
        {{ protocol }}://{{ domain }}{% url 'usersapp:password_reset_confirm' uidb64=uid token=token %}
    </a>
</p>
<p>If you didn't request a password reset, please ignore this email.</p>
<p>Thanks,</p>
<p>The Our Team</p>
{% endautoescape %}

src/usersapp/templates/usersapp/sign.html
{% extends "quotes/base.html" %}

{% block content %}

{% endblock %}

src/usersapp/templates/usersapp/signup.html
{% extends 'usersapp/base.html' %}
{% load static %}
{% block content %}

        <div class="container h-100">
            <div class="row d-flex justify-content-center align-items-center h-100">
                <div class="col-8 col-md-6 col-lg-4 col-xl-6">
                    <div class="card" style="border-radius: 15px; height: 800px; overflow-y: auto;">
                       <div class="card-body d-flex flex-column align-items-center">
                            <h3 class="text-uppercase text-center mb-2">Create an account</h3>

                            <form method="post" action="{% url 'usersapp:create_user_profile' %}">
                                {% csrf_token %}


                                <div class="form-outline d-flex justify-content-center mb-1">
                                    <!--                                    <input type="email" id="form3Example3cg" class="form-control form-control-lg"/>-->
                                    <label class="form-label">Your Email: {{ form.email }}</label>
                                    <span>{{form.errors.email}}</span>
                                </div>


                                <div class="form-outline d-flex justify-content-center mb-1">
                                    <!--                                    <input type="text" id="form3Example6cg" class="form-control form-control-lg"/>-->
                                    <label class="form-label">Your Username: {{ form.username }}</label>
                                    <span>{{form.errors.username}}</span>
                                </div>


                                <div class="form-outline d-flex justify-content-center mb-1">
                                    <!--                                    <input type="text" id="form3Example1cg" class="form-control form-control-lg"/>-->
                                    <label class="form-label">Your First Name: {{ form.first_name }}</label>
                                    <span>{{form.errors.first_name}}</span>
                                </div>


                                <div class="form-outline d-flex justify-content-center mb-1">
                                    <!--                                    <input type="text" id="form3Example2cg" class="form-control form-control-lg"/>-->
                                    <label class="form-label">Your Last Name: {{ form.last_name }}</label>
                                    <span>{{form.errors.last_name}}</span>
                                </div>


                                <div class="form-outline d-flex justify-content-center mb-1">
                                    <!--                                    <input type="password" id="form3Example4cg" class="form-control form-control-lg"/>-->
                                    <label class="form-label">Password: {{ form.password1 }}</label>
                                    <span>{{form.errors.password1}}</span>
                                </div>

                                <div class="form-outline d-flex justify-content-center mb-1">
                                    <!--                                    <input type="password" id="form3Example4cdg" class="form-control form-control-lg"/>-->
                                    <label class="form-label">Repeat your password: {{ form.password2 }}</label>
                                    <span>{{form.errors.password2}}</span>
                                </div>

                                <div class="form-check d-flex justify-content-center mb-2">
                                    <input class="form-check-input me-2" type="checkbox" value="" id="form2Example3cg"/>
                                    <label class="form-check-label" for="form2Example3cg">
                                        I agree all statements in <a href="{% url 'usersapp:terms' %}" class="text-body"><u>Terms of service</u></a>
                                    </label>
                                </div>

                                <div class="d-flex justify-content-center">
                                    <button class="btn btn-success btn-block btn-lg gradient-custom-4 text-body">
                                        Register
                                    </button>
                                </div>

                                <p class="text-center text-muted mt-3 mb-0">Have already an account?
                                    <a href="{% url 'usersapp:login_user' %}"
                                       class="fw-bold text-body"><u>Login
                                        here</u></a></p>

                            </form>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

src/usersapp/templates/usersapp/success.html
{% extends "usersapp/base.html" %}

{% block content %}

<div class="container-fluid me-2 pe-3">
        <div class="d-flex flex-column align-items-center">
            <button class="btn btn-success btn-block btn-lg gradient-custom-5 text-body col-3" type="button"><a href="{% url 'usersapp:main' %}">Success!</a></button>
        </div>
</div>
{% endblock %}

src/usersapp/templates/usersapp/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>